# Generated by Django 5.2.4 on 2025-07-15 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField(unique=True)),
                ('borough', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('service_zone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaxiTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField()),
                ('pickup_datetime', models.DateTimeField()),
                ('dropoff_datetime', models.DateTimeField()),
                ('passenger_count', models.IntegerField()),
                ('trip_distance', models.FloatField()),
                ('pickup_longitude', models.FloatField(blank=True, null=True)),
                ('pickup_latitude', models.FloatField(blank=True, null=True)),
                ('dropoff_longitude', models.FloatField(blank=True, null=True)),
                ('dropoff_latitude', models.FloatField(blank=True, null=True)),
                ('pickup_location_id', models.IntegerField(blank=True, null=True)),
                ('dropoff_location_id', models.IntegerField(blank=True, null=True)),
                ('fare_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mta_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tip_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tolls_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-pickup_datetime'],
                'indexes': [models.Index(fields=['pickup_datetime'], name='taxi_api_ta_pickup__4741ba_idx'), models.Index(fields=['dropoff_datetime'], name='taxi_api_ta_dropoff_dc7084_idx'), models.Index(fields=['pickup_location_id'], name='taxi_api_ta_pickup__a2d8ca_idx'), models.Index(fields=['dropoff_location_id'], name='taxi_api_ta_dropoff_541acf_idx')],
            },
        ),
    ]
