# Generated by Django 5.2.4 on 2025-08-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("tags", models.CharField(blank=True, max_length=200)),
                ("summary", models.TextField(blank=True)),
                ("content", models.TextField()),
            ],
        ),
    ]
